version: '2'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workflow
    stdin_open: true
    tty: true
    ports:
      - "5441:5432"